### ISSUE TITLE
Feature: Use the custom tsconfig.json file which specified in -p parameter

### ISSUE THREAD

**Issue by TimeBather** [shigma/dtsc#1]
Use the custom tsconfig.json file which specified in -p parameter
In current version,dtsc use the default config file `tsconfig.json`.But in some cases,we need to rename the `tsconfig.json` to `tsconfig.compile.json` or other names.

**Comment by shigma** [comment]
Thanks for your advice. I will support `dtsc -p` in the next minor version (estimated), which will solve your problem.
