### ISSUE TITLE
De-duplicate exports

### ISSUE THREAD

**Issue by idanran** [shigma/dtsc#2]
![image](https://user-images.githubusercontent.com/96647698/204128924-26363a41-ff91-468d-86b6-13025cc105f6.png)

**Comment by shigma** [comment]
It is not possible to dedupe exports, so we provide a `dtsc.exclude` configuration item to meet your needs.

**Comment by idanran** [comment]
> It is not possible to dedupe exports, so we provide a `dtsc.exclude` configuration item to meet your needs.

ok, thanks!
